apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow
  namespace: credit-risk
spec:
  replicas: 1
  selector:
    matchLabels: { app: mlflow }
  template:
    metadata:
      labels: { app: mlflow }
    spec:
      containers:
        - name: mlflow
          image: credit-risk-mlflow:0.1
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: mlflow-postgres-secret
          ports: [{ containerPort: 5000 }]
          volumeMounts:
            - name: mlartifacts
              mountPath: /mlartifacts
      volumes:
        - name: mlartifacts
          persistentVolumeClaim:
            claimName: mlartifacts
---
apiVersion: v1
kind: Service
metadata:
  name: mlflow
  namespace: credit-risk
spec:
  selector: { app: mlflow }
  ports: [{ port: 5000, targetPort: 5000 }]
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mlartifacts
  namespace: credit-risk
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 10Gi