services:
  superset:
    image: apache/superset:latest
    container_name: credit_risk_superset
    ports:
      - "8088:8088"
    env_file:
      - .env
    environment:
      SUPERSET_SECRET_KEY: ${SUPERSET_SECRET_KEY}
      SUPERSET_CONFIG_PATH: /app/pythonpath/superset_config.py
    volumes:
      - ./superset_config.py:/app/pythonpath/superset_config.py:ro
      - superset_home:/app/superset_home

volumes:
  superset_home: