-- Active: 1789383651116@@localhost@5432@credit_risk

-- credit_risk_production/postgres/credit_risk.sql

-- Schema
CREATE SCHEMA IF NOT EXISTS credit_risk;

-- Table: fully qualified as credit_risk.data
CREATE TABLE IF NOT EXISTS credit_risk.data (
    prospectid                         BIGINT       PRIMARY KEY,
    total_tl                           INTEGER,
    tot_closed_tl                      INTEGER,
    tot_active_tl                      INTEGER,
    total_tl_opened_l6m                INTEGER,
    tot_tl_closed_l6m                  INTEGER,
    pct_tl_open_l6m                    DOUBLE PRECISION,
    pct_tl_closed_l6m                  DOUBLE PRECISION,
    pct_active_tl                      DOUBLE PRECISION,
    pct_closed_tl                      DOUBLE PRECISION,
    total_tl_opened_l12m               INTEGER,
    tot_tl_closed_l12m                 INTEGER,
    pct_tl_open_l12m                   DOUBLE PRECISION,
    pct_tl_closed_l12m                 DOUBLE PRECISION,
    tot_missed_pmnt                    INTEGER,
    auto_tl                            INTEGER,
    cc_tl                              INTEGER,
    consumer_tl                        INTEGER,
    gold_tl                            INTEGER,
    home_tl                            INTEGER,
    pl_tl                              INTEGER,
    secured_tl                         INTEGER,
    unsecured_tl                       INTEGER,
    other_tl                           INTEGER,
    age_oldest_tl                      INTEGER,
    age_newest_tl                      INTEGER,
    time_since_recent_payment          INTEGER,
    time_since_first_deliquency        INTEGER,
    time_since_recent_deliquency       INTEGER,
    num_times_delinquent               INTEGER,
    max_delinquency_level              INTEGER,
    max_recent_level_of_deliq          INTEGER,
    num_deliq_6mts                     INTEGER,
    num_deliq_12mts                    INTEGER,
    num_deliq_6_12mts                  INTEGER,
    max_deliq_6mts                     INTEGER,
    max_deliq_12mts                    INTEGER,
    num_times_30p_dpd                  INTEGER,
    num_times_60p_dpd                  INTEGER,
    num_std                            INTEGER,
    num_std_6mts                       INTEGER,
    num_std_12mts                      INTEGER,
    num_sub                            INTEGER,
    num_sub_6mts                       INTEGER,
    num_sub_12mts                      INTEGER,
    num_dbt                            INTEGER,
    num_dbt_6mts                       INTEGER,
    num_dbt_12mts                      INTEGER,
    num_lss                            INTEGER,
    num_lss_6mts                       INTEGER,
    num_lss_12mts                      INTEGER,
    recent_level_of_deliq              INTEGER,
    tot_enq                            INTEGER,
    cc_enq                             INTEGER,
    cc_enq_l6m                         INTEGER,
    cc_enq_l12m                        INTEGER,
    pl_enq                             INTEGER,
    pl_enq_l6m                         INTEGER,
    pl_enq_l12m                        INTEGER,
    time_since_recent_enq              INTEGER,
    enq_l12m                           INTEGER,
    enq_l6m                            INTEGER,
    enq_l3m                            INTEGER,
    maritalstatus                      TEXT,
    education                          TEXT,
    age                                INTEGER,
    gender                             TEXT,
    netmonthlyincome                   INTEGER,
    time_with_curr_empr                INTEGER,
    pct_of_active_tls_ever             DOUBLE PRECISION,
    pct_opened_tls_l6m_of_l12m         DOUBLE PRECISION,
    pct_currentbal_all_tl              DOUBLE PRECISION,
    cc_utilization                     DOUBLE PRECISION,
    cc_flag                            INTEGER,
    pl_utilization                     DOUBLE PRECISION,
    pl_flag                            INTEGER,
    pct_pl_enq_l6m_of_l12m             DOUBLE PRECISION,
    pct_cc_enq_l6m_of_l12m             DOUBLE PRECISION,
    pct_pl_enq_l6m_of_ever             DOUBLE PRECISION,
    pct_cc_enq_l6m_of_ever             DOUBLE PRECISION,
    max_unsec_exposure_inpct           DOUBLE PRECISION,
    hl_flag                            INTEGER,
    gl_flag                            INTEGER,
    last_prod_enq2                     TEXT,
    first_prod_enq2                    TEXT,
    credit_score                       INTEGER,
    approved_flag                      TEXT,
    created_at                         TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Indexes MUST reference credit_risk.data
CREATE INDEX IF NOT EXISTS idx_credit_risk_data_approved_flag
    ON credit_risk.data (approved_flag);

CREATE INDEX IF NOT EXISTS idx_credit_risk_data_credit_score
    ON credit_risk.data (credit_score);